select * from customer limit 20


--01 What is the total revenue generated by male vs. female customer?
select gender,SUM(purchase_amount) as revenue
from customer
group by gender
--02 Which customers used, a discount but still spent more than the average purchase am